apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argo-cd
spec:
  project: spof-cluster
  sources:
    - chart: pihole
      repoURL: https://mojo2600.github.io/pihole-kubernetes/
      targetRevision: 2.27.0
      helm:
        releaseName: pihole
        valueFiles:
          - $values/values.yaml
    - repoURL: "https://github.com/SP0Fs/pihole-k8s.git"
      targetRevision: HEAD
      ref: values
    - repoURL: "https://github.com/SP0Fs/pihole-k8s.git"
      targetRevision: HEAD
      path: resources
  destination:
    server: "https://kubernetes.default.svc"
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
