apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc-pihole
  namespace: pihole
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
