kind: Service
apiVersion: v1
metadata:
  name: pihole-dns
  namespace: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  selector:
    app: pihole
  ports:
    - port: 53
      targetPort: 53
      name: pihole-dns-udp
      protocol: UDP
    - port: 53
      targetPort: 53
      name: pihole-dns-tcp
      protocol: TCP
    - port: 67
      targetPort: 67
      name: pihole-67-udp
      protocol: UDP
  type: LoadBalancer
  # You want to assign a fixed ip address
  # pihole will be used as a DNS server
  # on your network, and that needs to be a
  # well known/unchanging address.
  loadBalancerIP: 192.168.178.99
  sessionAffinity: ClientIP
