kind: Service
apiVersion: v1
metadata:
  name: pihole-dns
  namespace: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  selector:
    app: pihole
  ports:
    - port: 53
      targetPort: 53
      name: pihole-dns-udp
      protocol: UDP
      nodePort: 30053
    - port: 53
      targetPort: 53
      name: pihole-dns-tcp
      protocol: TCP
      nodePort: 30053
    - port: 67
      targetPort: 67
      name: pihole-67-udp
      protocol: UDP
      nodePort: 30067
  type: NodePort
  # loadBalancerIP: 192.168.178.99
  sessionAffinity: ClientIP
